app = "log-kimsymmons"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile.server"

[http_service]
  internal_port = 3001
  force_https = true

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"
